### PR TITLE
Pipeop learner and learnercv if a Graph and no id is used, collapse the ids of the Graph

### LINKED ISSUE #292: learner_cv construction fails if given a Graph and no id

### PR DESCRIPTION
**Pull request by sumny**
Closes #292

### CODE REVIEW

File: R/PipeOpLearner.R [hunk 1]
```diff
@@ -79,6 +79,12 @@
 PipeOpLearner = R6Class("PipeOpLearner", inherit = PipeOp,
   public = list(
     initialize = function(learner, id = if (is.character(learner)) learner else learner$id, param_vals = list()) {
```
Comment (mb706) [inline R/PipeOpLearner.R:81]: I think the solution here would be to have `id = NULL`, and then in the code
```r
private$.learner = as_learner(learner, clone = TRUE)  # merge master before doing this!
self$id = id %??% private$.learner$id
```
also add a tests pls
